
CC=g++
#CFLAGS=

dem_scope: dem_scope #not sure what all of these do
	$(CC) demo_localscope.cpp foo.cpp -o dem_scope
	
quiz_scope: quiz_scope
	$(CC) quiz_scope.cpp -o quiz_scope

demo_extlink: 
	$(CC) demo_extlink.cpp ext.cpp -o demo_extlink